version: "3.5"
networks:
  project3:
    name: project3
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.5.0.0/16
          ip_range: 10.5.0.0/24
          gateway: 10.5.0.1
services:
  # ==== KAFKA SETUP ====
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: project3-zookeeper
    networks:
      project3:
        ipv4_address: 10.5.0.2
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:2.5.0
    container_name: project3-kafka
    networks:
      project3:
        ipv4_address: 10.5.0.3
    ports:
      - 9092:9092
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://10.5.0.3:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  init-kafka:
    image: confluentinc/cp-kafka:6.1.1
    container_name: project3-init-kafka
    networks:
      project3:
        ipv4_address: 10.5.0.4
    depends_on:
      - kafka
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      # blocks until kafka is reachable
      kafka-topics --bootstrap-server kafka:9092 --list

      echo -e 'Creating kafka topics'
      kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic loan-request --replication-factor 1 --partitions 1
      kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic loan-reply --replication-factor 1 --partitions 1
      kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic loan-email --replication-factor 1 --partitions 1

      echo -e 'Successfully created the following topics:'
      kafka-topics --bootstrap-server kafka:9092 --list
      "
  # ==== KAFKA SETUP END ====

  # ==== RABBITMQ SETUP ====
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: project3-rabbitmq
    networks:
      project3:
        ipv4_address: 10.5.0.5
    ports:
        - 5672:5672
        - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: P@ssword!
    volumes:
        - ./rabbitmq/definitions.json:/opt/definitions.json:ro
        - ./rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro
  # ==== RABBITMQ SETUP END ====

  # ==== REDIS SETUP ====
  redis:
    image: redis:alpine
    container_name: project3-redis
    networks:
        project3:
          ipv4_address: 10.5.0.6
    ports:
      - 6379:6379
    environment:
      - REDIS_REPLICATION_MODE=master
    command: redis-server
  # ==== REDIS SETUP END ====

  # ==== API SERVICE SETUP ====
  api:
    build: ./service_api
    container_name: project3-api-service
    networks:
      project3:
        ipv4_address: 10.5.0.7
    ports:
      - 80:8080
  # ==== API SERVICE SETUP END ====

  # ==== CACHE SERVICE SETUP ====
  cache:
    build: ./service_cache
    container_name: project3-cache-service
    networks:
      project3:
        ipv4_address: 10.5.0.8
    ports:
      - 81:8080
  # ==== CACHE SERVICE SETUP END ====

  # ==== EMAIL SERVICE SETUP ====
  email:
    build: ./service_email
    container_name: project3-email-service
    networks:
      project3:
        ipv4_address: 10.5.0.9
    ports:
      - 82:8080
    environment:
      - EMAILPW= #SET EMAIL PW HERE!!
  # ==== EMAIL SERVICE SETUP END ====

  # ==== BANK SERVICE 1 SETUP ====
  bank1:
    build: ./service_bank_start
    container_name: project3-bank-service1
    networks:
      project3:
        ipv4_address: 10.5.0.10
    environment:
      - BANKID=1

  bank1-end:
    build: ./service_bank_end
    container_name: project3-bank-service1-end
    networks:
      project3:
        ipv4_address: 10.5.0.11
    environment:
      - BANKID=1
    
  # ==== BANK SERVICE 1 SETUP END ====

  # ==== BANK SERVICE 2 SETUP ====
  bank2:
    build: ./service_bank_start
    container_name: project3-bank-service2
    networks:
      project3:
        ipv4_address: 10.5.0.12
    environment:
      - BANKID=2

  bank2-end:
    build: ./service_bank_end
    container_name: project3-bank-service2-end
    networks:
      project3:
        ipv4_address: 10.5.0.13
    environment:
      - BANKID=2
  # ==== BANK SERVICE 2 SETUP END ====
