version: "3.5"
networks:
  project3:
    name: project3
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.5.0.0/16
          ip_range: 10.5.0.0/24
          gateway: 10.5.0.1
          aux_addresses:
            kafka: 10.5.0.2
            zookeeper: 10.5.0.3
            rabbitmq: 10.5.0.4
            api: 10.5.0.5
services:
  # ==== KAFKA SETUP ====
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: project3-zookeeper
    networks:
      - project3
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:2.5.0
    container_name: project3-kafka
    networks:
      - project3
    ports:
      - 9092:9092
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://10.5.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  init-kafka:
    image: confluentinc/cp-kafka:6.1.1
    container_name: project3-init-kafka
    networks:
      - project3
    depends_on:
      - kafka
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      # blocks until kafka is reachable
      kafka-topics --bootstrap-server kafka:9092 --list

      echo -e 'Creating kafka topics'
      kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic bank-request --replication-factor 1 --partitions 1
      kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic bank-reply --replication-factor 1 --partitions 1
      kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic loan-email --replication-factor 1 --partitions 1

      echo -e 'Successfully created the following topics:'
      kafka-topics --bootstrap-server kafka:9092 --list
      "
  # ==== KAFKA SETUP END ====

  # ==== RABBITMQ SETUP ====
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: project3-rabbitmq
    networks:
        - project3
    ports:
        - 5672:5672
        - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: P@ssword!
    volumes:
        - ./rabbitmq/definitions.json:/opt/definitions.json:ro
        - ./rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro
  # ==== RABBITMQ SETUP END ====

  # ==== API SETUP ====
  api:
    build: ./api
    container_name: project3-api
    networks:
        - project3
    ports:
      - 80:8080
  # ==== API SETUP END ====