version: "3.8"

networks:
  lan:

services:
  mssql:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      SA_PASSWORD: "P@ssword123"
      ACCEPT_EULA: "Y"
    networks:
      - lan

  mssqlcli:
    image: mcr.microsoft.com/mssql-tools:latest
    command: bash
    networks:
      - lan

  ef:
    build: ./
    command: "./wait-for-it.sh mssql:1433 -- dotnet run --no-launch-profile --project MiniProject2.EF"
    networks:
      - lan 

  webapi:
    build: ./
    command: "./wait-for-it.sh mssql:1433 -- dotnet run --no-launch-profile --project MiniProject2.WebApi"
    environment:
      ASPNETCORE_URLS: "http://*:80"
    networks:
      - lan
    ports:
      - 8000:80

  servicebook:
    build: ./
    command: "./wait-for-it.sh mssql:1433 -- dotnet run --no-launch-profile --project MiniProject2.ServiceBook"
    environment:
      ASPNETCORE_URLS: "http://*:80"
    networks:
      - lan

  serviceexam:
    build: ./
    command: "./wait-for-it.sh mssql:1433 -- dotnet run --no-launch-profile --project MiniProject2.ServiceExam"
    environment:
      ASPNETCORE_URLS: "http://*:80"
    networks:
      - lan

  servicegrade:
    build: ./
    command: "./wait-for-it.sh mssql:1433 -- dotnet run --no-launch-profile --project MiniProject2.ServiceGrade"
    environment:
      ASPNETCORE_URLS: "http://*:80"
    networks:
      - lan
  
  servicestudent:
    build: ./
    command: "./wait-for-it.sh mssql:1433 -- dotnet run --no-launch-profile --project MiniProject2.ServiceStudent"
    environment:
      ASPNETCORE_URLS: "http://*:80"
    networks:
      - lan

  serviceteacher:
    build: ./
    command: "./wait-for-it.sh mssql:1433 -- dotnet run --no-launch-profile --project MiniProject2.ServiceTeacher"
    environment:
      ASPNETCORE_URLS: "http://*:80"
    networks:
      - lan